export enum OrderStatusEnum {
	PENDING = 'PENDING',
	ACCEPTED = 'ACCEPTED',
	DECLINED = 'DECLINED',
	PAYMENT_PENDING = 'PAYMENT_PENDING',
	PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
	IN_PRODUCTION = 'IN_PRODUCTION',
	READY = 'READY',
	IN_TRANSIT = 'IN_TRANSIT',
	COMPLETED = 'COMPLETED'
}
