export const ROUTES = {
	HOME: '/',
	REGISTER: '/register',
	LOGIN: '/login',
	FORGOT_PASSWORD: 'forgot-password',
	BARNAHUSES: '/barnahuses',
	ADD_BARNAHUS: '/barnahuses/add',
	EDIT_BARNAHUS: '/barnahuses/edit/',
	ADMINS: '/admins',
	ADD_ADMINS: '/admins/add',
	EDIT_ADMINS: '/admins/edit/',
	MASTER_ADMINS: '/master-admins',
	ADD_MASTER_ADMINS: '/master-admins/add',
	EDIT_MASTER_ADMINS: '/master-admins/edit/',
	PRACTITIONERS: '/practitioners',
	ADD_PRACTITIONERS: '/practitioners/add',
	EDIT_PRACTITIONERS: '/practitioners/edit/',
	MANAGE_CONTENT: '/manage-content',
	CONTENT: '/content',
	LANGUAGES: '/languages',
	ADD_LANGUAGES: '/languages/add',
	ADD_CONTENT: '/manage-content/add',
	CASE_FILES: '/case-files',
	ADD_CASE_FILES: '/case-files/add',
	EDIT_CASE_FILES: '/case-files/edit',
	CASE_JOURNEY: '/case-journey',
	SETTINGS: '/settings'
}
